/// Autogenerated file. Editing is pointless.
#pragma once
#include "utils.h"

namespace rk
{
	struct parameters {
		double m,k,f;
	};
	struct FirstOrderSystem {
		parameters params; 
		FirstOrderSystem(parameters const& p) : params{ p } {}
		virtual ~FirstOrderSystem() = default;
		virtual vec<1> operator()(double z, vec<1> const& y) const = 0;
	};

}
